//! The symbols HTML writes by name.

/// The symbol an HTML name stands for: the names a message is likely to
/// hold, which are punctuation, signs and the accented letters of Latin-1.
/// A soft hyphen and the marks of direction stand for nothing. The joiners
/// are kept: one makes two emoji one, and both shape words in some scripts.
pub(super) fn named(name: &str) -> Option<&'static str> {
    const NAMES: &[(&str, &str)] = &[
        ("amp", "&"),
        ("lt", "<"),
        ("gt", ">"),
        ("quot", "\""),
        ("apos", "'"),
        ("nbsp", " "),
        ("ensp", " "),
        ("emsp", " "),
        ("thinsp", " "),
        ("shy", ""),
        ("zwnj", "\u{200c}"),
        ("zwj", "\u{200d}"),
        ("lrm", ""),
        ("rlm", ""),
        ("ndash", "\u{2013}"),
        ("mdash", "\u{2014}"),
        ("hellip", "\u{2026}"),
        ("bull", "\u{2022}"),
        ("middot", "\u{b7}"),
        ("lsquo", "\u{2018}"),
        ("rsquo", "\u{2019}"),
        ("sbquo", "\u{201a}"),
        ("ldquo", "\u{201c}"),
        ("rdquo", "\u{201d}"),
        ("bdquo", "\u{201e}"),
        ("laquo", "\u{ab}"),
        ("raquo", "\u{bb}"),
        ("lsaquo", "\u{2039}"),
        ("rsaquo", "\u{203a}"),
        ("prime", "\u{2032}"),
        ("Prime", "\u{2033}"),
        ("dagger", "\u{2020}"),
        ("Dagger", "\u{2021}"),
        ("permil", "\u{2030}"),
        ("copy", "\u{a9}"),
        ("reg", "\u{ae}"),
        ("trade", "\u{2122}"),
        ("sect", "\u{a7}"),
        ("para", "\u{b6}"),
        ("deg", "\u{b0}"),
        ("euro", "\u{20ac}"),
        ("pound", "\u{a3}"),
        ("yen", "\u{a5}"),
        ("cent", "\u{a2}"),
        ("curren", "\u{a4}"),
        ("times", "\u{d7}"),
        ("divide", "\u{f7}"),
        ("plusmn", "\u{b1}"),
        ("minus", "\u{2212}"),
        ("ne", "\u{2260}"),
        ("le", "\u{2264}"),
        ("ge", "\u{2265}"),
        ("asymp", "\u{2248}"),
        ("infin", "\u{221e}"),
        ("micro", "\u{b5}"),
        ("frac12", "\u{bd}"),
        ("frac14", "\u{bc}"),
        ("frac34", "\u{be}"),
        ("sup1", "\u{b9}"),
        ("sup2", "\u{b2}"),
        ("sup3", "\u{b3}"),
        ("larr", "\u{2190}"),
        ("uarr", "\u{2191}"),
        ("rarr", "\u{2192}"),
        ("darr", "\u{2193}"),
        ("harr", "\u{2194}"),
        ("lArr", "\u{21d0}"),
        ("rArr", "\u{21d2}"),
        ("check", "\u{2713}"),
        ("iexcl", "\u{a1}"),
        ("iquest", "\u{bf}"),
        ("ordf", "\u{aa}"),
        ("ordm", "\u{ba}"),
        ("not", "\u{ac}"),
        ("brvbar", "\u{a6}"),
        ("uml", "\u{a8}"),
        ("Agrave", "\u{c0}"),
        ("Aacute", "\u{c1}"),
        ("Acirc", "\u{c2}"),
        ("Atilde", "\u{c3}"),
        ("Auml", "\u{c4}"),
        ("Aring", "\u{c5}"),
        ("AElig", "\u{c6}"),
        ("Ccedil", "\u{c7}"),
        ("Egrave", "\u{c8}"),
        ("Eacute", "\u{c9}"),
        ("Ecirc", "\u{ca}"),
        ("Euml", "\u{cb}"),
        ("Igrave", "\u{cc}"),
        ("Iacute", "\u{cd}"),
        ("Icirc", "\u{ce}"),
        ("Iuml", "\u{cf}"),
        ("ETH", "\u{d0}"),
        ("Ntilde", "\u{d1}"),
        ("Ograve", "\u{d2}"),
        ("Oacute", "\u{d3}"),
        ("Ocirc", "\u{d4}"),
        ("Otilde", "\u{d5}"),
        ("Ouml", "\u{d6}"),
        ("Oslash", "\u{d8}"),
        ("Ugrave", "\u{d9}"),
        ("Uacute", "\u{da}"),
        ("Ucirc", "\u{db}"),
        ("Uuml", "\u{dc}"),
        ("Yacute", "\u{dd}"),
        ("THORN", "\u{de}"),
        ("szlig", "\u{df}"),
        ("agrave", "\u{e0}"),
        ("aacute", "\u{e1}"),
        ("acirc", "\u{e2}"),
        ("atilde", "\u{e3}"),
        ("auml", "\u{e4}"),
        ("aring", "\u{e5}"),
        ("aelig", "\u{e6}"),
        ("ccedil", "\u{e7}"),
        ("egrave", "\u{e8}"),
        ("eacute", "\u{e9}"),
        ("ecirc", "\u{ea}"),
        ("euml", "\u{eb}"),
        ("igrave", "\u{ec}"),
        ("iacute", "\u{ed}"),
        ("icirc", "\u{ee}"),
        ("iuml", "\u{ef}"),
        ("eth", "\u{f0}"),
        ("ntilde", "\u{f1}"),
        ("ograve", "\u{f2}"),
        ("oacute", "\u{f3}"),
        ("ocirc", "\u{f4}"),
        ("otilde", "\u{f5}"),
        ("ouml", "\u{f6}"),
        ("oslash", "\u{f8}"),
        ("ugrave", "\u{f9}"),
        ("uacute", "\u{fa}"),
        ("ucirc", "\u{fb}"),
        ("uuml", "\u{fc}"),
        ("yacute", "\u{fd}"),
        ("thorn", "\u{fe}"),
        ("yuml", "\u{ff}"),
        ("OElig", "\u{152}"),
        ("oelig", "\u{153}"),
        ("Scaron", "\u{160}"),
        ("scaron", "\u{161}"),
    ];
    NAMES
        .iter()
        .find(|(known, _)| *known == name)
        .map(|(_, symbol)| *symbol)
}
